name: run E2E Tests

on: ['pull_request']

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: ignitenode03
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgres://docker:docker@localhost:5432/ignitenode03?schema=public"